{
 "title": "COVID",
 "time": { "from": "now-5M", "to": "now" },
 "templating": {
  "list": [
   { "name": "measurement", "label": "measurement", "query": "SHOW MEASUREMENTS" },
   {
    "name": "state",
    "label": "state",
    "query": "SHOW TAG VALUES ON covid WITH KEY = \"state_province\""
   },
   {
    "name": "county",
    "label": "county",
    "query": "SHOW TAG VALUES ON covid WITH KEY = \"county\" WHERE state_province = '$state'"
   },
   { "name": "measurement_2", "label": "Measurement (Diff)", "query": "SHOW MEASUREMENTS" },
   {
    "name": "state_2",
    "label": "State (Diff)",
    "query": "SHOW TAG VALUES ON covid WITH KEY = \"state_province\""
   },
   {
    "name": "county_2",
    "label": "County (Diff)",
    "query": "SHOW TAG VALUES ON covid WITH KEY = \"county\" WHERE state_province = '$state_2'"
   }
  ]
 },
 "panels": [
  {
   "title": "Total ${measurement} in ${state} (LOG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total ${measurement}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$county$/" }
     ]
    },
    {
     "alias": "New ${measurement} per day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=~", "value": "/^$state$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$county$/" }
     ]
    }
   ]
  },
  {
   "title": "Total ${measurement_2} in ${state_2} (${county_2})  (LOG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total ${measurement_2}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_2$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=~", "value": "/^$state_2$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$county_2$/" }
     ]
    },
    {
     "alias": "New ${measurement_2} per day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement_2$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=~", "value": "/^$state_2$/" },
      { "condition": "AND", "key": "county", "operator": "=~", "value": "/^$county_2$/" }
     ]
    }
   ]
  },
  { "title": "Washington Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Deaths vs Confirmed King County",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed Cases per Day King County",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=", "value": "Washington" },
      { "condition": "AND", "key": "county", "operator": "=", "value": "King" }
     ]
    },
    {
     "alias": "New Deaths per day King County",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "deaths",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=", "value": "Washington" },
      { "condition": "AND", "key": "county", "operator": "=", "value": "King" }
     ]
    }
   ]
  },
  {
   "title": "Cases in WA and King County",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Cases in WA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=", "value": "Washington" }
     ]
    },
    {
     "alias": "Total Cases per Day in WA",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1d" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=", "value": "Washington" }
     ]
    },
    {
     "alias": "Total Cases in King County",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=", "value": "Washington" },
      { "condition": "AND", "key": "county", "operator": "=", "value": "King" }
     ]
    },
    {
     "alias": "Total Cases per Day in King County",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "state_province", "operator": "=", "value": "Washington" },
      { "condition": "AND", "key": "county", "operator": "=", "value": "King" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed Cases (US)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Confirmed Cases",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "New Cases per Day",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "confirmed",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "24h" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=", "value": "US" }
     ]
    }
   ]
  }
 ]
}